include common.conf
# startup_session ./sessions/main
# os_window_name kitty_main
watcher session_save.py

enabled_layouts fat:bias=80,splits,stack

allow_remote_control yes
listen_on unix:/tmp/kitty_{kitty_pid}.sock
