live_config_reload = true

[font]
size = 10.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[window]
decorations = "none"
opacity = 1

[window.class]
general = "alacritty"
instance = "alacritty"

[colors.bright]
black = "0x3e4452"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0x5c6370"
text = "0x2c323c"

[colors.normal]
black = "0x2c323c"
blue = "0x4fa6ed"
cyan = "0x48b0bd"
green = "0x8ebd6b"
magenta = "0xbf68d9"
red = "0xe55561"
white = "0xa0a8b7"
yellow = "0xe2b86b"

[colors.primary]
background = "0x1a1c23"
foreground = "0xa0a8b7"

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Command"
