#!/bin/bash

args="${@:1}"

if command -v /usr/bin/nvimpager >/dev/null; then
    NVIMPAGER=/usr/bin/nvimpager
elif command -v /usr/local/bin/nvimpager > /dev/null; then
    NVIMPAGER=/usr/local/bin/nvimpager
else
    echo "'nvimpager' not found in path"
    exit 1
fi

$NVIMPAGER $args -p <&0
