arch = { packages = [
  "accountsservice",
  "alsa-firmware",
  "alsa-plugins",
  "awesome-terminal-fonts",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-obex",
  "btrfs-assistant",
  "cachyos-fish-config",
  "cachyos-hello",
  "cachyos-hooks",
  "cachyos-kernel-manager",
  "cachyos-keyring",
  "cachyos-micro-settings",
  "cachyos-mirrorlist",
  "cachyos-packageinstaller",
  "cachyos-plymouth-bootanimation",
  "cachyos-plymouth-theme",
  "cachyos-rate-mirrors",
  "cachyos-settings",
  "cachyos-snapper-support",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cachyos-wallpapers",
  "cantarell-fonts",
  "chwd",
  "cryptsetup",
  "device-mapper",
  "diffutils",
  "dmraid",
  "dnsmasq",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "efitools",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "ffmpegthumbnailer",
  "flatpak",
  "fsarchiver",
  "gst-libav",
  "gst-plugin-va",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "hdparm",
  "hwdetect",
  "hwinfo",
  "inetutils",
  "iptables",
  "jfsutils",
  "less",
  "lib32-mesa",
  "lib32-opencl-mesa",
  "lib32-vulkan-radeon",
  "libdvdcss",
  "libgsf",
  "libopenraw",
  "limine",
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  "linux-cachyos",
  "linux-cachyos-headers",
  "linux-cachyos-lts",
  "linux-cachyos-lts-headers",
  "logrotate",
  "lsb-release",
  "lsscsi",
  "lvm2",
  "man-pages",
  "mdadm",
  "meld",
  "mkinitcpio",
  "mtools",
  "netctl",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "noto-fonts-cjk",
  "nss-mdns",
  "opencl-mesa",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "perl",
  "pkgfile",
  "playerctl",
  "plocate",
  "polkit-kde-agent",
  "poppler-glib",
  "power-profiles-daemon",
  "pv",
  "python",
  "python-defusedxml",
  "python-packaging",
  "rebuild-detector",
  "sof-firmware",
  "sudo",
  "sysfsutils",
  "texinfo",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ufw",
  "ufw-extras",
  "usb_modeswitch",
  "usbutils",
  "uwsm",
  "vlc-plugins-all",
  "which",
  "wpa_supplicant",
  "xdg-user-dirs",
  "xfsprogs",
  "xl2tpd",
  "xorg-xwayland",
] }
flatpak = { repos = [
  { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/" } },
  { name = "user:cosmic", options = { url = "https://apt.pop-os.org/cosmic/" } },
] }
