arch = [
  "7zip",
  "aichat",
  "alsa-utils",
  "amd-ucode",
  "android-studio",
  "android-tools",
  "annotator-git",
  "ansible",
  "arduino-avr-core",
  "arduino-cli",
  "arduino-ide-bin",
  "arduino-language-server",
  "atuin",
  "avrdude",
  "base",
  "base-devel",
  "bat",
  "batsignal",
  "bc",
  "bear",
  "bind",
  "blender",
  "blender-benchmark",
  "blueman",
  "bluez-utils",
  "breeze-icons",
  "brightnessctl",
  "brother-mfc-j491dw",
  "btdu",
  "btop",
  "btrfs-progs",
  "ccls",
  "chromium",
  "claude-code",
  "clickup",
  "code",
  "cpupower",
  "cronie",
  "cups",
  "cups-pdf",
  "dasel",  # Serial data file converter
  "dconf-editor",
  "dialog",
  "direnv",
  "dmidecode",
  "docker",
  "docker-buildx",
  "docker-compose",
  "dracut",
  "dust",
  "easyeffects",
  "efibootmgr",
  "endless-sky-high-dpi",
  "evince",
  "eyedropper",
  "fastfetch",
  "fd",
  "firefox-developer-edition",
  "firewalld",
  "fish",
  "fisher",
  "font-manager",
  "fprintd",
  "framework-system",
  "framework-tool-tui",
  "fw-fanctrl",
  "fwupd",
  "fzf",
  "gammastep",
  "gdb",
  "gdm",
  "git",
  "git-delta",
  "git-filter-repo",
  "git-lfs",
  "github-cli",
  "glab",
  "godot",
  "gogcli",
  "gst-plugin-pipewire",
  "gvfs-afc",
  "gvfs-dnssd",
  "gvfs-google",
  "gvfs-gphoto2",
  "gvfs-mtp",
  "gvfs-nfs",
  "gvfs-onedrive",
  "gvfs-smb",
  "gvfs-wsdd",
  "handbrake",
  "hip-runtime-amd",
  "htop",
  "httpie",
  "hunspell-en_us",
  "icon-library",
  "imagemagick",
  "inkscape",
  "inter-font",
  "iotop",
  "ipython",
  "iwd",
  "jq",
  "just",
  "kalker-bin",
  "kdeconnect",
  "keyd",
  "kicad",
  "kitty-git",
  "kvantum",
  "kvantum-qt5",
  "kvantum-theme-orchis-git",
  "kvantum-theme-whitesur-git",
  "kwalletmanager",
  "lazygit",
  "libiodbc",
  "libpulse",
  "libwebp-utils",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-lts",
  "loupe",
  "lsd",
  "lshw",
  "lsof",
  "lsp-plugins",
  "man-db",
  "maplemono-ttf",
  "mesa-utils",
  "meson",
  "metapac",
  "nautilus",
  "neovim",
  "network-manager-applet",
  "networkmanager",
  "nextcloud-client",
  "nix",
  "nmap",
  "notion-app-electron",
  "noto-fonts",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "nvtop",
  "obsidian",
  "obsidian-cli-bin",
  "opencode",
  "orchis-theme",
  "paru",
  "pavucontrol",
  "pdfarranger",
  "pipewire",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "plymouth",
  "pnpm",
  "powertop",
  "procs",
  "pwgen",
  "qbittorrent",
  "qemu-audio-spice",
  "qemu-base",
  "qemu-hw-display-qxl",
  "qemu-hw-display-virtio-gpu",
  "qemu-hw-display-virtio-gpu-gl",
  "qemu-hw-usb-host",
  "qemu-ui-gtk",
  "qemu-ui-spice-app",
  "qmk",
  "qt5-wayland",
  "qt5ct",
  "qt6-imageformats",
  "qt6-wayland",
  "qt6ct",
  "rclone",
  "reflector",
  "rink",
  "ripgrep",
  "rsync",
  "rust-analyzer",
  "rustup",
  "rygel",
  "sane-airscan",
  "signal-desktop",
  "simple-scan",
  "smartmontools",
  "snap-pac",
  "snapper",
  "spacenavd",
  "sslscan",
  "starship",
  "strace",
  "sushi",  # Gnome nautilus previewer
  "system-config-printer",
  "tailscale",
  "tdrop",
  "tea",
  "tealdeer",
  "texlive-fontsextra",
  "tokei",
  "totem",
  "tree",
  "trunk",
  "ttf-ibm-plex",
  "ttf-jetbrains-mono-nerd",
  "ttf-lato",
  "ttf-liberation",
  "ttf-lilex-nerd",
  "ttf-material-symbols-variable-git",
  "ttf-readex-pro",
  "ttf-rubik-vf",
  "ttf-space-mono-nerd",
  "tuned",
  "tuned-ppd",
  "typescript",
  "unrar",
  "unzip",
  "upower",
  "uv",
  "vimix-cursors",
  "virt-manager",
  "virt-viewer",
  "virtualbox",
  "vlc",
  "vlc-plugin-ffmpeg",
  "vulkan-radeon",
  "wakeonlan",
  "wasm-pack",
  "watchexec",
  "waypipe",
  "webp-pixbuf-loader",  # for previews of webp in Gnome
  "wget",
  "whois",
  "wine",
  "wine-gecko",
  "wine-mono",
  "winetricks",
  "wireplumber",
  "wl-clipboard",
  "xdg-utils",
  "xf86-video-amdgpu",
  "xf86-video-ati",
  "xorg-server",
  "xorg-xeyes",
  "xorg-xhost",
  "xorg-xinit",
  "xorg-xlsclients",
  "yaak-bin",
  "yay",  # backup in case paru breaks
  "yelp",
  "yq",
  "zip",
  "zoxide",
]
cargo = [
  "cargo-binstall",
  "cargo-feature",
  "cargo-tree",
  "create-tauri-app",
  "rudric",
  "sqlx-cli",
  "todui",
]
flatpak = [
  "app.bluebubbles.BlueBubbles",
  "com.bambulab.BambuStudio",
  "com.devolutions.remotedesktopmanager",
  "com.github.tchx84.Flatseal",
  "com.moonlight_stream.Moonlight",
  "com.protonvpn.www",
  "com.slack.Slack",
  "it.mijorus.gearlever",
  "org.gimp.GIMP",
  "org.indii.mendingwall",
  "org.onlyoffice.desktopeditors",
  # "org.gimp.GIMP.Plugin.Resynthesizer",
]
