arch = [
  "gnome-backgrounds",
  "gnome-calculator",
  "gnome-calendar",
  "gnome-characters",
  "gnome-clocks",
  "gnome-connections",
  "gnome-console",
  "gnome-contacts",
  "gnome-control-center",
  "gnome-disk-utility",
  "gnome-font-viewer",
  "gnome-keyring",
  "gnome-logs",
  "gnome-maps",
  "gnome-menus",
  "gnome-remote-desktop",
  "gnome-shell",
  "gnome-shell-extension-appindicator",
  "gnome-shell-extension-battery-health-charging-git",
  "gnome-shell-extension-blur-my-shell",
  "gnome-shell-extension-gsconnect",
  "gnome-shell-extension-pano-bin",
  "gnome-shell-extension-pop-shell-git",
  "gnome-shell-extension-unite",
  "gnome-software",
  "gnome-system-monitor",
  "gnome-text-editor",
  "gnome-tour",
  "gnome-tweaks",
  "gnome-user-docs",
  "gnome-user-share",
  "gnome-weather",
]
