arch = { packages = [
  "aquamarine",
  "cliphist",
  "cmake",
  "cursor-clip-git",
  "fuzzel",
  "grimblast-git",
  "hypridle",
  "hyprland",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprshot",
  "kanshi",
  "nautilus",
  "sushi",  # Gnome nautilus previewer
  "swaync",
  "swayosd",
  "udiskie",
  "waybar",
  "xdg-desktop-portal-hyprland",
  "nwg-look",
  "wayland-protocols",
  "quickshell-git",
  "sddm",
] }
