#!/bin/bash

BLUEZCARD=$(pactl list cards short | awk '/bluez/{print $2}')
pactl set-card-profile "$BLUEZCARD" a2dp-sink
pactl set-card-profile "$BLUEZCARD" headset-head-unit
pactl set-card-profile "$BLUEZCARD" a2dp-sink
