#!/usr/bin/env bash

max_volume=150
volume=0
mute=false

info=$(pactl -f json list sinks)
mute=$(jq -r '.[0].mute' <<< "$info")
volume=$(jq -r '.[0].volume."front-left".value_percent' <<< "$info" | tr -d '%')

function volume_up() {
    if [ "$mute" = "true" ]; then
        toggle_mute
    else
        # swayosd-client --max-volume $max_volume --output-volume raise
        if [ "$volume" -ge $(( max_volume - 5 )) ]; then
            pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
        else
            pactl set-sink-volume @DEFAULT_SINK@ +5%
        fi
    fi
}

function volume_down() {
    if [ "$mute" = "true" ]; then
        toggle_mute
    else
        # swayosd-client --max-volume $max_volume --output-volume lower
        pactl set-sink-volume @DEFAULT_SINK@ -5%
    fi
}

function toggle_mute() {
    # swayosd-client --max-volume $max_volume --output-volume mute-toggle
    pactl set-sink-mute @DEFAULT_SINK@ toggle
}

case "$1" in
up)
    volume_up
    ;;
down)
    volume_down
    ;;
mute)
    toggle_mute
    ;;
*)
    echo "Subcommand $1 invalid"
    exit 1
    ;;
esac
