#!/usr/bin/env bash

max_volume=150
volume=0
mute=false
step=10

info=$(pactl -f json list sinks)
mute=$(pactl -f json get-sink-mute @DEFAULT_SINK@ | jq -r '.mute')
volume=$(pactl -f json get-sink-volume @DEFAULT_SINK@ | jq -r '.volume."front-left".value_percent' | tr -d '%')

function volume_up() {
    if [ "$mute" = "true" ]; then
        toggle_mute
    else
        # swayosd-client --max-volume $max_volume --output-volume raise
        if [ "$volume" -ge $((max_volume - 5)) ]; then
            pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
        else
            pactl set-sink-volume @DEFAULT_SINK@ +$step%
        fi
    fi
}

function volume_down() {
    if [ "$mute" = "true" ]; then
        toggle_mute
    else
        # swayosd-client --max-volume $max_volume --output-volume lower
        pactl set-sink-volume @DEFAULT_SINK@ -$step%
    fi
}

function toggle_mute() {
    # swayosd-client --max-volume $max_volume --output-volume mute-toggle
    pactl set-sink-mute @DEFAULT_SINK@ toggle
}

case "$1" in
up)
    volume_up
    ;;
down)
    volume_down
    ;;
mute)
    toggle_mute
    ;;
*)
    echo "Subcommand $1 invalid"
    exit 1
    ;;
esac
