#!/bin/bash

ags -q || true
ags &

function exit {
    ags -q
}

trap exit EXIT

inotifywait -e close_write -m -r --exclude .git . |
while read -r directory events filename; do
    echo "reload"
    ags -q
    ags &
done
