#!/bin/bash

pkill ags || true
ags &

function exit {
    pkill ags
}

trap exit EXIT

inotifywait -e close_write -m -r --exclude .git . |
while read -r directory events filename; do
    echo "reload"
    pkill ags
    ags &
done
