splash = false

ipc = off

wallpaper {
    monitor = desc:Microstep MSI MAG341CQ
    path = ~/Pictures/Wallpapers/Purple-Sky-Mountain.jpg
}

wallpaper {
    monitor = eDP-2
    path = ~/Pictures/Wallpapers/LakeInMountains.jpg 
}
