source = ~/.config/hypr/conf/*

# bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-2, disable"
# bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-2, $internalMonitor"

# Init
exec-once = hyprpaper 
exec-once = kanshi
# exec-once = wl-paste --type text --watch cliphist store #Stores only text data
# exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once = udiskie &
exec-once = hypridle
exec-once = nextcloud --background
exec-once = systemctl --user start hyprpolkitagent
exec-once = quickshell -c lg
exec-once = [workspace 1] kitty --session sessions/main
exec-once = cursor-clip --daemon
exec-once = hyprctl setcursor WinSur-dark-cursors 24
exec-once = batsignal -b -w 20 -c 10 -d 5
exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11



xwayland {
    force_zero_scaling = true
}

input {
    follow_mouse = 2
    sensitivity = 0.6 # -1.0 - 1.0, 0 means no modification.
    scroll_factor = 1.5

    repeat_rate = 30
    repeat_delay = 250

    touchpad {
        natural_scroll = no
        scroll_factor = 0.6
        clickfinger_behavior = true
        disable_while_typing = true
    }

    kb_options = compose:ralt
}

cursor {
    no_hardware_cursors = 1
    no_warps = true
}

general {
    # https://wiki.hyprland.org/Configuring/Variables/

    gaps_in = 5
    gaps_out = 10
    border_size = 0
    # border_size = 1
    # col.active_border = rgb(444444)
    # col.inactive_border = rgb(333333)

    layout = master

    allow_tearing = true

    resize_on_border = true
}

layout {
    single_window_aspect_ratio = 13 8
}

decoration {
    # https://wiki.hyprland.org/Configuring/Variables/

    rounding = 10

    blur {
        enabled = yes
        size = 3
        passes = 2
        new_optimizations = on
        ignore_opacity = true
        popups = true
    }

    # dim_inactive = true
    # dim_strength = 0.2
    # dim_special = 0.2
}

animations {
    enabled = yes

    animation = windows, 1, 2, default
    animation = layers, 1, 2, default, fade
    animation = workspaces, 1, 2, default, slide
}

master {
    new_status = slave
    mfact = 0.5
    slave_count_for_center_master = 0
}

gestures {
    workspace_swipe_invert = false
    workspace_swipe_cancel_ratio = 0.25
}

gesture = 3, horizontal, scale: 0.35, workspace

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
    vfr = true
}

debug {
    disable_logs = false
}


# .config/hypr/hyprland.conf
plugin {
    hyprexpo {
        columns = 3
        gap_size = 10
        workspace_method = center current
        skip_empty = true

        # gesture_distance = 300
    }
}
