[pyprland]
plugins = ["scratchpads"]

[scratchpads.dropdown]
command = "kitty --class dropdown_terminal --override background_opacity=0.8 zellij a -c dropdown"
class = "dropdown_terminal"
position = "5% 45px"
size = "90% 60%"
multi = false
animation = "fromTop"
hide_delay = 0.3
