enabled_backends = ["arch", "cargo", "flatpak"]
hostname_groups_enabled = true

[arch]
package_manager = "paru"

[flatpak]

[cargo]
binstall = true

[hostname_groups]
kratos = ["default", "hyprland", "gnome", "cachyos-kernel", "linux-kernel"]
chad = ["default", "hyprland", "cachyos"]
