$scriptDir = $HOME/.config/hypr/scripts

bind = SUPER SHIFT, d, exec, hyprctl keyword monitor "eDP-2, disable"
bind = SUPER SHIFT, u, exec, hyprctl keyword monitor "eDP-2, $internalMonitor"

$mainMod = SUPER

bind = CONTROL SHIFT, return, exec, kitty --session sessions/main
bind = $mainMod SHIFT, r, exec, hyprctl reload
bind = CONTROL SHIFT, w, killactive, 
bind = CONTROL ALT, escape, exec, hyprctl kill
bind = CONTROL ALT, q, exec, hyprctl kill
bind = CONTROL SHIFT, x, exit, 
bind = $mainMod, f, togglefloating, 
bind = $mainMod, p, pin, 
bind = CONTROL, space, exec, fuzzel
bind = CONTROL ALT, V, exec, cursor-clip
bind = CONTROL SHIFT, d, exec, hyprctl dpms on

# bind = ALT, TAB, workspace, previous
bind = ALT, TAB, focuscurrentorlast
bind = $mainMod, return, layoutmsg, swapwithmaster
bind = $mainMod, m, fullscreen, 1
bind = $mainMod shift, m, fullscreen, 0

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = ALT, 1, workspace, 1
bind = ALT, 2, workspace, 2
bind = ALT, 3, workspace, 3
bind = ALT, 4, workspace, 4
bind = ALT, 5, workspace, 5
bind = ALT, 6, workspace, 6
bind = ALT, 7, workspace, 7
bind = ALT, 8, workspace, 8
bind = ALT, 9, workspace, 9
bind = ALT, 0, workspace, 10
bind = ALT, S, togglespecialworkspace, special

bind = ALT SHIFT, 1, movetoworkspacesilent, 1
bind = ALT SHIFT, 2, movetoworkspacesilent, 2
bind = ALT SHIFT, 3, movetoworkspacesilent, 3
bind = ALT SHIFT, 4, movetoworkspacesilent, 4
bind = ALT SHIFT, 5, movetoworkspacesilent, 5
bind = ALT SHIFT, 6, movetoworkspacesilent, 6
bind = ALT SHIFT, 7, movetoworkspacesilent, 7
bind = ALT SHIFT, 8, movetoworkspacesilent, 8
bind = ALT SHIFT, 9, movetoworkspacesilent, 9
bind = ALT SHIFT, 0, movetoworkspacesilent, 10
bind = ALT SHIFT, s, movetoworkspacesilent, special

# Resize mode
bind= $mainMod, E, submap, resize
submap=resize
binde= , l, resizeactive, 10 0
binde= , h, resizeactive, -10 0
binde= , k, resizeactive, 0 -10
binde= , j, resizeactive, 0 10
binde= SHIFT , l, resizeactive, 20 0
binde= SHIFT , h, resizeactive, -20 0
binde= SHIFT , k, resizeactive, 0 -20
binde= SHIFT , j, resizeactive, 0 20
bind=, escape, submap, reset 
bind= $mainMod, E, submap, reset 
submap=reset

# bind = ALT, l, workspace, e+1
# bind = ALT, h, workspace, e-1
bind = , mouse_right, workspace, e+1
bind = , mouse_left, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


# bind = ALT, T, exec, $dropdownCommand
# bind = ALT, T, exec, pypr toggle dropdown
bind = ALT, T, exec, kitten quick-access-terminal --detach=yes
bind = ALT SHIFT, T, exec, procs kitty-quick-access --json | jq -r '.[0].PID' | xargs kill -9


# Screenshots
bind = CONTROL SHIFT, 3, exec, hyprshot -z -o ~/Pictures/Screenshots -m output -m active
bind = CONTROL SHIFT, 4, exec, hyprshot -z -o ~/Pictures/Screenshots -m region
bind = CONTROL SHIFT, 5, exec, hyprshot -z -o ~/Pictures/Screenshots -m window

# Media keys
bind = , XF86AudioPlay, exec, $scriptDir/play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrevious, exec, playerctl previous
bind = SHIFT, XF86AudioRaiseVolume, exec, $scriptDir/resync_a2dp
bind = SHIFT, XF86AudioLowerVolume, exec, $scriptDir/resync_hfp
binde = , XF86AudioRaiseVolume, exec, $scriptDir/volume up
binde = , XF86AudioLowerVolume, exec, $scriptDir/volume down
binde = , XF86AudioMute, exec, $scriptDir/volume mute
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
