windowrule {
    name = floats
    match:class = (org.gnome.NautilusPreviewer|xdg-desktop-portal-gtk|Emulator)
    float = on
}

layerrule {
    name = dropdown
    match:namespace = kitty-quick-access
    animation = slide top
}

layerrule {
    name = blur and alpha
    match:class = .*
    blur = on
    blur_popups = on
    ignore_alpha = 0.1
}

layerrule {
  name = selection
  match:namespace = selection
  no_anim = on
  blur = off
}

