# workspace = w[t1]m[desc:Microstep MSI MAG341CQ], gapsout:10 600
# workspace = w[t1]m[eDP-2], gapsout:10 60
# workspace = r[1-1]w[t1], gapsout:10
workspace = 1, layout:monocle

# workspace = r[1-6], persistent:true
