[alacritty.files]
"alacritty.yml" = "~/.config/alacritty.yml"

[fish.files]
fish = { target = "~/.config/fish", type = "symbolic", recurse = false }

[helix.files]
helix = { target = "~/.config/helix", type = "symbolic", recurse = false }

[hypr.files]
hypr = { target = "~/.config/hypr", type = "symbolic", recurse = false }

[karabiner.files]
karabiner = { target = "~/.config/karabiner", type = "symbolic", recurse = false }

[keyd.files]
keyd = { target = "/etc/keyd", type = "symbolic", recurse = false, owner = "root" }

[leftwm.files]
leftwm = { target = "~/.config/leftwm", type = "symbolic", recurse = false }

[nushell.files]
nushell = "~/.config/nushell"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[nvimpager.files]
nvimpager = { target = "~/.config/nvimpager", type = "symbolic", recurse = false }

[rofi.files]
rofi = { target = "~/.config/rofi", type = "symbolic", recurse = false }

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[tealdeer.files]
tealdeer = { target = "~/.config/tealdeer", type = "symbolic", recurse = false }

[waybar.files]
waybar = { target = "~/.config/waybar", type = "symbolic", recurse = false }

[zellij.files]
zellij = { target = "~/.config/zellij", type = "symbolic", recurse = false }
