packages = [
  "alacritty",
  "fish",
  "helix",
  "hypr",
  "ideavim",
  "keyd",
  "leftwm",
  "lsd",
  "nushell",
  "nvim",
  "nvimpager",
  "rofi",
  "starship",
  "tealdeer",
  "waybar",
  "zellij",
  "git",
]
